docs: variable documentation
UCSD-E4E/smartfin-fw3 pull request #134
Opened 2024-11-22 01:07 UTC by ihagad

2024-11-22 19:02 UTC, ucsd-e4e-role requested changes
What we talked about...

2024-11-22 19:52 UTC, ntlhui reviewed
See @ucsd-e4e-role 's comments

2025-01-06 19:22 UTC, ntlhui requested changes

2025-01-06 19:22 UTC, ntlhui commented on src/cellular/dataCollection.cpp
> +     * x, y, and z axis in g scaled up by 16834
Does this mean that if `acc` has the value `{1, 0, 0}`, I should interpret this as [0.000059, 0, 0] g's of acceleration?

Conversely, should I expect [1, 0, 0] g's of acceleration to be represented at `{16834, 0, 0}`?

2025-01-07 16:45 UTC, ntlhui requested changes

2025-01-07 16:45 UTC, ntlhui commented on src/cellular/dataCollection.cpp
> +     * x, y, and z axis in g scaled up by 16834
when you specify this, please add units for the real-world value so that it is unambiguously the real-world value vs the stored representation.

2025-01-07 21:26 UTC, ntlhui requested changes

2025-01-07 21:26 UTC, ntlhui commented on src/cellular/dataCollection.cpp
> +     * x, y, and z axis in g scaled up by 16834
This ends up being confusing - are we stating that the values as stored in memory are directly interpretable as G's of acceleration?

Additionally, in line 26, I think you have the wrong constant.

One suggested wording might be this:
```
acc[i] = acceleration[i] * 16384, where `acceleration` is the acceleration in G's (multiple of Earth gravity), and acc is the stored representation, stored as `int32_t`.  Thus, acc[i] = 16384 = 1 G.
```

Consider updating the other field documentation to be similar.

2025-01-13 22:39 UTC, ntlhui commented
Is this ready for review?

2025-01-27 06:08 UTC, ihagad commented on src/cellular/dataCollection.cpp
> +     * 1 = 0.15 degree/second
I forgot to change the units, its should be uT. Is that the only inconsistency?

2025-01-27 17:33 UTC, ntlhui approved these changes

2025-01-27 17:34 UTC, ucsd-e4e-role approved these changes

2025-01-27 17:34 UTC, merged

2025-01-27 23:34 UTC, ucsd-e4e-role commented
:tada: This PR is included in version 3.6.1 :tada:

The release is available on [GitHub release](https://github.com/UCSD-E4E/smartfin-fw3/releases/tag/v3.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: