Temperature sensor
UCSD-E4E/smartfin-fw3 pull request #19
Opened 2023-08-03 21:39 UTC by emilybthorpe

2023-08-23 17:19 UTC, ntlhui commented
@emilybthorpe please resolve conflicts

2023-08-25 00:31 UTC, ntlhui requested changes

2023-08-25 00:31 UTC, ntlhui commented on src/cli/menuItems/debugCommands.cpp
>  }
Missing trailing newline

2023-08-28 20:04 UTC, emilybthorpe commented on src/cli/cliDebug.cpp
> +
Fixed

2023-08-28 20:05 UTC, emilybthorpe commented on src/cli/flog.hpp
> +    FLOG_CHARGER_REMOVED  =0x0702
Sounds good

2023-08-28 20:07 UTC, emilybthorpe commented on src/cli/menuItems/debugCommands.cpp
> +    }
Fixed

2023-08-28 20:07 UTC, emilybthorpe commented on src/cli/menuItems/debugCommands.cpp
>  }
Fixed

2023-08-28 20:10 UTC, emilybthorpe commented on src/system.cpp
>      return 1;
Removed

2023-08-28 20:13 UTC, emilybthorpe commented on src/temperature/max31725.h
I'm not sure where the source or what to mark the liscence as, as well as there is no version number listed. What would you suggest having?

2023-08-28 20:25 UTC, ntlhui commented on src/temperature/max31725.h
https://os.mbed.com/teams/MaximIntegrated/code/MAX31725_Accurate_Temperature_Sensor//file/b4fdbbe79036/max31725.h/

2023-08-28 22:30 UTC, ntlhui approved these changes

2023-08-28 22:30 UTC, ntlhui commented on README.md
> +Max 31725       | 2019    | Copyright Max 2019 | https://os.mbed.com/teams/MaximIntegrated/code/MAX31725_Accurate_Temperature_Sensor//file/b4fdbbe79036/max31725.h/ | temperature/
Per that website, all code is licensed under Apache.

2023-08-29 03:03 UTC, ntlhui approved these changes

2023-08-29 03:03 UTC, merged