Watersensor
UCSD-E4E/smartfin-fw3 pull request #28
Opened 2023-08-24 22:19 UTC by emilybthorpe

2023-08-28 22:31 UTC, emilybthorpe commented
After switching to the smartfin that Jordan was testing with, all manufacturing tests pass

2023-08-29 03:00 UTC, ntlhui commented
please update branch

2023-08-29 03:04 UTC, ntlhui commented
Please resolve conflicts

2023-08-29 20:10 UTC, ntlhui requested changes

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +    digitalWrite(water_detect_en_pin, HIGH);
Note that current measurement on a PicoScope indicates a neg pulse width of 1.010 ms with 1.289 us standard deviation over 100 measurements.

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +        samples_taken_since_reset++;
Add conditional body braces

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +    // out of the water!
This should go inside the condition body

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +    // in the water!
This should go inside the condition body

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +    // nothing has changed, return current status
This should go inside the condition body

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +// gets the current in/out of water status (return true = in water, false = out)
Use Doxygen style

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +// forces the in/out of water status.  Usefule because of hystersis
Use Doxygen style

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +    digitalWrite(water_detect_en_pin, HIGH);
This should use `WaterSensor::getCurrentReading`

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +// set the low detection percentage of the moving window for hystersis
Use Doxygen style

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +        return false;
Add braces

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +// set the high detection percentage of the moving window for hystersis
Use Doxygen style

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +WaterSensor::WaterSensor(uint8_t water_detect_en_pin_to_set, uint8_t water_detect_pin_to_set, uint8_t window_size, uint8_t array_size) : water_detect_en_pin(water_detect_en_pin_to_set), water_detect_
Split into multiple lines

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.cpp
> +        return (location + offset);
Add braces

2023-08-29 20:10 UTC, ntlhui commented on src/watersensor/waterSensor.hpp
Update docs to Doxygen style

2023-08-29 20:44 UTC, emilybthorpe commented on src/mfgTest/mfgTest.hpp
> +    static int(* MFG_TEST_TABLE[])(void);
Probably not, going to mark as private

2023-09-11 21:01 UTC, ntlhui commented
Fixes #8

2023-09-11 22:22 UTC, ntlhui approved these changes

2023-09-11 22:24 UTC, merged